### ISSUE TITLE
Error building tip of SDL_sound

### ISSUE THREAD

**Issue by ericoporto** [sezero/SDL_sound#4]
Hi,

I am having the following error trying to build the tip of the hg repository, but I can't find the bugzilla

https://hg.icculus.org/icculus/SDL_sound/archive/4b78007f035f.tar.gz
(MD5 hash ff2448f5a789ae2a07636c243d8f8780)

```
libSDL2_sound.a(sndfile.c.o): in function `new_CSoundFile':
src/libmodplug/sndfile.c:92: undefined reference to `CSoundFile_ReadABC'
src/libmodplug/sndfile.c:93: undefined reference to `CSoundFile_ReadMID'
src/libmodplug/sndfile.c:94: undefined reference to `CSoundFile_ReadPAT'
```

Do you know what could cause it?

**Comment by sezero** [comment]
I can't reproduce this: Are you absolutely sure that your source tree is clean
and doesn't have any remnants from any old revisions?

**Comment by ericoporto** [comment]
it's actually a new computer, no leftovers, but for some reason it stopped happening, so I am closing.
