### ISSUE TITLE
Emscripten `error: undefined symbol: SDL_uclibc_exp` 

### ISSUE THREAD

**Issue by ericoporto** [sezero/SDL_sound#6]
Commit 8d47f56dbdffd9d69431bcfb3568f4b4566be7e2 currently breaks building SDL_sound on Emscripten (assuming #5 is dealt with in some way) at link time:

```
error: undefined symbol: SDL_uclibc_exp (referenced by top-level compiled C/C++ code)
warning: Link with `-s LLD_REPORT_UNDEFINED` to get more information on undefined symbols
warning: To disable errors for undefined symbols use `-s ERROR_ON_UNDEFINED_SYMBOLS=0`
warning: _SDL_uclibc_exp may need to be added to EXPORTED_FUNCTIONS if it arrives from a system library
Error: Aborting compilation due to previous errors
```

The problem is it will now require the symbol `SDL_uclibc_exp` be exported (`-s EXPORTED_FUNCTIONS=['_SDL_uclibc_exp']`) from SDL2, but SDL2 from Emscripten ports doesn't do this.

For now, the easy way on Emscripten is to remove the line `#define exp SDL_exp` in the file `src/SDL_sound_vorbis.c` - I am doing so with `sed` in cmake. Maybe the right way is to fix on Emscripten ports upstream.

**Comment by sezero** [comment]
This sounds like an issue with emscripten build of SDL2: Are you sure that
the emscripten build of SDL2 is building and including src/libm/e_exp.c?

**Comment by sezero** [comment]
Note to @icculus: Since you guys killed bugzilla (shame), where do
the SDL_sound bug reports should go? I don't mind some people using
my mirror, but you should add it to your github watch list to be notified.

**Comment by ericoporto** [comment]
> This sounds like an issue with emscripten build of SDL2: Are you sure that
> the emscripten build of SDL2 is building and including src/libm/e_exp.c?

As far as I can tell it isn't. The port build code is done through a weird python builder in Emscripten core though, I reported the error in the ports and will see what is answered there.

**Comment by sezero** [comment]
OK, closing as invalid.

**Comment by ericoporto** [comment]
Fix merged on upstream!

**Comment by icculus** [comment]
> Note to @icculus: Since you guys killed bugzilla (shame), where do the SDL_sound bug reports should go?

I'm trying to decide if this is staying in Mercurial (and thus bugzilla.icculus.org) or move to GitHub.

I'll decide soon.
